src/components/Table/index.tsx, src/components/Table/style.module.scss
=> [GH-19] Fix some css

src/components/Checkbox/index.tsx, src/components/Checkbox/style.module.scss, src/components/Table/EditableCell.tsx, src/components/Table/helper.ts, src/components/TimeTable/Subject.module.scss, src/examples/Table.tsx, src/styles/color.css
=> [GH-19] Use custom checkbox and rename color

src/components/Checkbox/style.module.scss
=> [GH-19] edit css checkbox

src/examples/Table.tsx
=> [GH-19] Fix warnning

src/App.tsx, src/components/Modal/index.tsx, src/components/Modal/style.module.scss, src/examples/Modal.tsx, src/styles/color.css
=> [GH-22] Modal component

.vscode/settings.json, src/App.tsx, src/components/Button/index.tsx, src/components/Button/style.module.scss, src/examples/Button.tsx, src/styles/color.css
=> [GH-6] Button component added

src/pages/Menu/RoomPage/helper.ts
=> [GH-15] Uppercase

src/components/Layout/Updated.module.scss, src/components/Layout/Updated.tsx, src/components/Layout/helper.ts, src/components/Text/index.tsx, src/pages/Menu/SettingPage/index.tsx, src/pages/Menu/SettingPage/style.module.scss
=> [GH-4] Stamp time to sidebar when update

src/pages/Menu/SettingPage/index.tsx
resolve ceoss-kmitl/ceoss-backend#59
=> [GH-59] Add vice-dean  and SIIE director name

src/pages/Menu/SettingPage/index.tsx
resolve ceoss-kmitl/ceoss-backend#62
=> [GH-62] Update setting UI

src/pages/Menu/SubjectPage/helper.ts
resolve ceoss-kmitl/ceoss-backend#66
=> Update Subject UI

src/components/Button/index.tsx, src/pages/WorkloadPage/components/WorkloadAdder.module.scss, src/pages/WorkloadPage/components/WorkloadAdder.tsx, src/pages/WorkloadPage/components/WorkloadAdderHelper.ts, src/pages/WorkloadPage/helper.ts, src/pages/WorkloadPage/index.tsx
=> [GH-49] Can now add new workload

src/pages/Menu/TeacherPage/helper.ts
close ceoss-kmitl/ceoss-backend#78
=> [GH-78] Edit teacher table

src/components/TimeTable/helper.ts, src/components/TimeTable/index.tsx, src/pages/WorkloadPage/components/WorkloadAdder.tsx, src/pages/WorkloadPage/components/WorkloadAdderHelper.ts
=> [GH-70] Add degree form-item

src/components/Layout/MyHeader.tsx
=> Show academic year & semester at the top bar

src/components/Table/Drawer.tsx, src/pages/Menu/TeacherPage/helper.ts
=> [GH-77] Refine some ui

src/components/Checkbox/index.tsx, src/components/DatePicker/index.tsx, src/components/Select/style.module.scss, src/components/TimeTable/Workload.tsx, src/components/TimeTable/helper.ts, src/components/TimeTable/index.tsx, src/index.tsx, src/pages/WorkloadPage/components/ExternalTeacherDrawer.module.scss, src/pages/WorkloadPage/components/ExternalTeacherDrawer.tsx, src/pages/WorkloadPage/components/ExternalTeacherDrawerHelper.ts, src/pages/WorkloadPage/helper.ts, src/pages/WorkloadPage/index.tsx, src/pages/WorkloadPage/style.module.scss
=> [GH-68] External teacher config drawer

src/pages/WorkloadPage/helper.ts
close ceoss-kmitl/ceoss-backend#111
=> [GH-106] Change teacher workload endpoint

package.json, src/App.tsx, src/components/Button/index.tsx, src/components/Layout/MyHeader.tsx, src/components/Layout/helper.ts, src/components/RoomTable/Drawer.tsx, src/components/RoomTable/RoomDrawer.module.scss, src/components/RoomTable/RoomDrawer.tsx, src/components/RoomTable/helper.ts, src/contexts/AcademicYearContext.tsx, src/pages/AutomaticRoomPage/components/BigSearch.module.scss, src/pages/AutomaticRoomPage/components/BigSearch.tsx, src/pages/AutomaticRoomPage/helper.ts, src/pages/AutomaticRoomPage/index.tsx, src/pages/AutomaticRoomPage/style.module.scss, src/pages/WorkloadPage/components/BigSearch.module.scss, src/pages/WorkloadPage/components/BigSearch.tsx, src/pages/WorkloadPage/components/ExternalTeacherDrawer.tsx, src/pages/WorkloadPage/helper.ts, src/pages/WorkloadPage/index.tsx, yarn.lock
close ceoss-kmitl/ceoss-backend#105
=> [GH-105] Update overall UX/UI

src/apis/subject.ts, src/apis/workload.ts, src/pages/AssistantDocumentPage/components/Drawer.module.scss, src/pages/AssistantDocumentPage/components/Drawer.tsx, src/pages/AssistantDocumentPage/components/DrawerHelper.ts, src/pages/AssistantDocumentPage/hooks/useDrawerForm.ts
=> [GH-10] Improve UI TA system, multiple selection calendar

src/App.tsx, src/components/Layout/helper.ts, src/pages/AssistantDocumentPage/hooks/useDownloadFile.ts, src/pages/Menu/AssistantPage/index.tsx
close ceoss-kmitl/ceoss-backend#25
=> [GH-25] Remove some unused code

src/apis/workload.ts, src/pages/AutomaticRoomPage/components/AdderDrawerHelper.ts, src/pages/Menu/SubjectPage/helper.ts
close ceoss-kmitl/ceoss-backend#121
=> [GH-121] Add checkbox requiredRoom into Subject menu

src/components/Notification/index.tsx
=> [GH-91] Fix - notification endless seeMore

src/pages/AssistantDocumentPage/components/DownloaderDrawer.module.scss, src/pages/AssistantDocumentPage/components/DownloaderDrawer.tsx, src/pages/AssistantDocumentPage/components/Drawer.module.scss, src/pages/AssistantDocumentPage/components/Drawer.tsx, src/pages/AssistantDocumentPage/components/DrawerHelper.ts
=> [GH-106] Fix TA UI - wrong dayList count

src/components/Layout/helper.ts
close ceoss-kmitl/ceoss-backend#132
=> [GH-132] Web scrap v2

src/pages/Menu/SettingPage/helper.ts, src/pages/Menu/SettingPage/index.tsx
=> [GH-129] fix modal setting
